### ISSUE TITLE
React native - ReferenceError: Property 'React' doesn't exist

### ISSUE THREAD

**Issue by blrichards** [PostHog/posthog-js-lite#298]
## Bug description

As of version 3.3.7, posthog-react-native package throws the following error:

```
ReferenceError: Property 'React' doesn't exist
  at PostHogProvider (/node_modules/posthog-react-native/lib/posthog-react-native/src/PostHogProvider.js:1:3637)
  at renderWithHooks (/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3657:22)
  at beginWork (/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8752:32)
  at performUnitOfWork (/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8317:23)
  at workLoopSync (/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8210:54)
...
(20 additional frame(s) were not displayed)
```

## How to reproduce

1. Install posthog-react-native 3.3.7 or 3.3.8 into an expo project
2. Run the app on simulator or on device

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

## Additional context

Our team reverted back to version 3.3.6 and everything works fine.

**Comment by marandaneto** [comment]
hey @blrichards thanks for raising this issue and sorry about that.
I think https://github.com/PostHog/posthog-js-lite/pull/299 should resolve it although everything works well locally.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-js-lite/releases/tag/posthog-react-native-v3.3.9 should fix it hopefully 🤞
